#!/usr/bin/env python3
"""Generate the deterministic catalog for the flat portable skill library."""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    category: str


SCALAR = re.compile(r"^[^\n\[\]{}]+$")
CATEGORY = re.compile(r"^[a-z][a-z0-9-]*$")


def field(header: str, key: str, *, indent: int = 0) -> str:
    prefix = " " * indent
    matches = re.findall(rf"^{re.escape(prefix + key)}: (.+)$", header, re.MULTILINE)
    if len(matches) != 1 or not SCALAR.fullmatch(matches[0]):
        raise ValueError(f"frontmatter must contain one string {key}")
    return matches[0].strip()


def metadata_category(header: str, path: Path) -> str:
    blocks = re.findall(r"^metadata:\s*\n((?:  [^\n]*\n?)*)", header, re.MULTILINE)
    if len(blocks) != 1:
        raise ValueError(f"frontmatter must contain one metadata mapping: {path}")
    try:
        category = field(blocks[0], "category", indent=2)
    except ValueError as error:
        raise ValueError(f"metadata must contain one direct string category: {path}") from error
    if not CATEGORY.fullmatch(category):
        raise ValueError(f"metadata.category must be a lowercase kebab-case string: {path}")
    return category


def load_skills(root: Path) -> list[Skill]:
    skills_dir = root / ".agents/skills"
    paths = sorted(skills_dir.glob("*/SKILL.md"))
    if not paths:
        raise ValueError(f"no flat skills found under {skills_dir}")
    skills: list[Skill] = []
    for path in paths:
        text = path.read_text()
        if not text.startswith("---\n") or text.count("---\n") < 2:
            raise ValueError(f"missing frontmatter: {path}")
        header = text.split("---\n", 2)[1]
        name = field(header, "name")
        description = field(header, "description")
        category = metadata_category(header, path)
        if name != path.parent.name:
            raise ValueError(f"skill name does not match directory: {path}")
        skills.append(Skill(name, description, category))
    names = [skill.name for skill in skills]
    if len(names) != len(set(names)):
        raise ValueError("duplicate skill names")
    return skills


def title(category: str) -> str:
    return " ".join(part.upper() if part in {"qa", "api"} else part.capitalize() for part in category.split("-"))


def render(skills: list[Skill]) -> str:
    grouped: dict[str, list[Skill]] = defaultdict(list)
    for skill in skills:
        grouped[skill.category].append(skill)
    lines = [
        "# Agent Skills Catalog",
        "",
        "Generated by `.agents/scripts/generate-catalog.py`. Do not edit by hand.",
        "",
    ]
    for category in sorted(grouped, key=lambda value: title(value).casefold()):
        lines.extend((f"## {title(category)}", ""))
        for skill in sorted(grouped[category], key=lambda value: value.name):
            lines.append(f"- [`{skill.name}`](skills/{skill.name}/SKILL.md) — {skill.description}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    target = root / ".agents/catalog.md"
    try:
        expected = render(load_skills(root))
    except (OSError, ValueError) as error:
        print(f"generate-catalog: {error}", file=sys.stderr)
        return 2
    if args.check:
        actual = target.read_text() if target.exists() else ""
        if actual != expected:
            print(f"generate-catalog: stale catalog: {target}", file=sys.stderr)
            return 1
        print(f"catalog is current: {len(load_skills(root))} skills")
        return 0
    target.write_text(expected)
    print(f"generated {target} with {len(load_skills(root))} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
